const { text } = require("express");

class MessageService {
  constructor() {
    this.messages = this.getDefaultMessages();
  }
  
  getDefaultMessages() {
    return [
      { _id: "1", text: "The world deserves someone like you who speaks life into others, who has dreams to change the world and fully devotes themselves to helping others. You are one of the brightest minds I know and you bring so much joy and light into the world. I want you to know that you are seen and loved. I pray that everything you do is blessed and that I get to see you making your mark in this world is a blessing in itself. Here's day 1 of 22. 💗", order: 0 },
      { _id: "2", text: "If ambition was a person it would be you. I've never met someone so driven and passionate about the things that they love. You inspire me each and every day. You always push me to do the things that I love and to never give up even when I'm so done with it. You are such a rock and I hope that fire in you never dies. I'm so proud of the person you are and the person you continue to be everyday. Here's to day 2 of 22💗", order: 1 },
      { _id: "3", text: "It's very rare to find someone who wears his heart on his sleeve like you do. You never keep me guessing on where we are or how you feel and you're always honest about that. You don't mince your words when you speak about your values or faith. You're firm but also carry alot of grace with you. You're all the things they say love to be; kind, patient, selfless and many more. I'm grateful to be part of that love you carry so dearly. Here's to day 3 of 22💗", order: 2 },
      { _id: "4", text: "One of the things that drew me to you was your faith. Believing in something greater than your self or the world as strongly as you do shows so much about your charachter. You carry that with you so proudly and so firmly. I love that you try to share pieces of that with me and you slowly bring me into your world. It’s one of the things that I never expected from you but it’s also one of the things that draw me closer to you everyday. Here’s to day 4 of 22💗", order: 3 },
      { _id: "5", text: "Being with you makes me calm down in so many ways. I’m not someone used to reassuarance. I usually cringe so much from people pouring their hearts out to me. But from you it’s like a warm hug, what keeps me moving through the days. You remind me that I’m not too much and that you’re always here. You always hold my hand through the days that feel so bleak. I don’t doubt alot when you’re with me because you always remind me that I can do anything I put my mind to. That I shouldn’t give up and that you’ll always be next to me. You’re my light and I can only hope to be the same for you. Here’s to day 5 of 22💗", order: 4 },
      { _id: "6", text: "Most people don’t like change. I mean even you sometimes😭. But whenever I’ve mentioned something that I don’t like or makes me feel some type of way you always make it right. Granted most times I don’t even see the unreasonableness in my claims but you never complain about it. You go out of your way to make me happy even if it’s the littlest thing. You pay so much attention to details that I usually miss. You always say that you know me better than myself.(I still heavily doubt that) but you’re well on your way there. You give me so much grace and patience that I don’t give myself a lot. You make me realize that things don’t have to be perfect for them to work. You keep me grounded because Lord knows I love to fly sometimes. You’re the voice in my head that says everything will be okay even when I don’t believe it. I adore how you’re able to be a voice of reason every time and still have compassion as well. Dealing with me isn’t easy but somehow you always make me feel like I’m not doing much even when I feel like I’ve over the top. I love you! Here’s to day 6 of 22💗", order: 5 },
      { _id: "7", text: "I know I’m the funny person in this relationship ofcourse but you make me laugh sometimes. Even though I take things so seriously sometimes. Your light hearted banter keeps me going. I don’t take the little  moments that we have together for granted. I don’t think I’ve stopped smiling since we met. Even if we have our downs the ups are worth more. You remind me that there’s always joy around me because you don’t stop calling me that anyway and I don’t want you to honestly. You’ve become the best part of my days and nights. What I look foward to after a long day. I don’t think it’s possible to have bad days when you exist in my life. I pray that I make your days brighter and lighter and that you always feel happy by my side. Well I know you do cause you always show you’re 32 teeth around me😭. All in all you’re my happiness and I love that I get to experience the joy you carry around everyday. Here’s to day 7 of 22💗", order: 6 },
      { _id: "8", text: "I know I call you a patient person alot but it’s barely enough to describe you. You carry yourself with so much grace and it shows in everything that you do. The way you talk and how you present yourself even when you’re upset is just a small example of that. It something that makes loving you the easiest thing to do. You give so much grace to the people around you and I know because I feel it everyday. You make want to become a better person and sometimes just have a little bit of the grace you have. I hope that you remember to give yourself the same grace that you show others, to go east on yourself sometimes and to rest whenever you need to. Even if you forget I’ll always be here to remind you to breathe and relax. I hope that in the love I give you, you also feel grace, that you know that you don’t have to be perfect because I love you with every bit and you should never forget that. Here’s to day 8 of 22💗", order: 7},
      { _id: "9", text: "You have this fighting spirit that I really admire. Most days it keeps me going in my own individual pursuits. When ever I feel tired or like giving up I just imagine what would Thuo do and giving up is never an option. I know I say that you inspire me a lot but having someone in my corner who’s always rooting for me everyday is what pushes me to do more for myself and for us. You’ve show me through how you live your life that there’s always something to look forward to and something to fight for. You listen to me when I complain about something that’s not going right and know just the words to say to make me fight for what I want. Everyday with you makes me have a clear vision of my life. A life that I want to have with you and one that I want to build. You make me feel celebrated of my achievements even when I don’t feel like they’re much. You push me to be a better version of myself everyday. I love you because I already see the traits of who I want to be in you and I see that our goals always align. I wouldn’t want anyone else cheering me on if it wasn’t you. In return I’ll always be here to cheer you on and tell you how proud of you I am everyday. In these 4 months that we’ve been getting to know each other I’ve not only seen you grow everyday but also seen you push yourself to limits I didn’t even know was possible. You’re everything I want and need and more and I’m always here to tell you I’m proud of you. Here’s to day 9💗", order: 8},
      { _id: "10", text: "I think my favourite part of being with you is just spending time with you. Taking a nap in between school because I need a break from the day or just sitting in silence with you. It brings me so much peace and joy. It makes me feel same. The moments when you look at me with the kindest eyes and even without saying anything and I can feel so much love held within that gaze. I’ve always wanted a soft love where I feel safe and you’ve given me that. I’m grateful everyday to get to experience the gentle person that you are and pure love that you have to give. Here’s to day 10💗", order: 9 },
      { _id: "11", text: "Halfway there already. Time is moving too fast for my liking but every second spent loving you is worth it. From the first day we met till now I wouldn’t choose a better person to experience this life with. You supplement my bad days with good ones, my sad times with happy ones and my lonely ones with love and comfort. There’s not a person in this world I would rather spend time with other than you. Missing you is both a blessing and a curse cause I would spend every waking second with you but longing for you is a unique experience. I love you!! Happy day 11 of 22💗", order: 10 },
      { _id: "12", text: "Another day another dollar!! This one came in a bit late but better late than never. I think today is one of those days that I’m grateful to have you. As someone who’s used to taking on the world alone you remind me that I don’t have to do that. You keep me aligned and make me know that I’m cared for. Slowly you’ve helped me bring down my walls and when I constantly try to rebuild them you take down real quick. You give me strength to go on everyday and I’m forever grateful for that. Sometimes I may not see what you see in me but I’m glad to have someone who looks at me with so much compassion and love. A great part of why this year has been great for me is because I’ve done it with you by my side. Most if not all of the accomplishments I’ve had this year are cause you’ve held me down in more ways than I could ever imagine and held me accountable with so much love. You’re my rock! Here’s to say 12 of 22💗", order: 11 },
      { _id: "13", text: "One of my greater moments in life is seeing you smile. You bring so much joy (ironical Ik)into my world. Every laugh we share, every joke you crack and every smile that creeps up on you makes loving you worth it even more. You truly make my life have more meaning and you give me something special to look forward to everyday. I hope to always keep that fire burning inside you and that spark that you have alive. I enjoy every moment that I share with you. Idk how different life would have been without you this year but I’m glad that I don’t need to know that. You make every day worth it and being loved by you is more than anyone (me) could ever ask for. Here’s to day 13 of 22💗", order: 12 },
      { _id: "14", text: "I think the best part about being with you is getting to know myself better. I’ve said time and time again that you make me a better person but I don’t think you understand just how much. You make me learn about my feelings more and recognize different patterns in my life. You make me want to learn more about your world just to see how I can fit. You make calm which is usually rare since my mind is always racing. You make me learn how to love beyond what I knew love was. You taught me that’s it’s more than a feeling but a choice. You make the world a kinder place for everyone who gets to experience life with you. Learning more about you, myself and us has been an interesting experience but one I wouldn’t change. You give me space to grow and figure things out while constantly reminding me that you’re always there. I count you twice each time I count my blessings. Here’s to day 14 of 22💗", order: 13 },
      { _id: "15", text: "Starting this series I didn’t imagine that the days would go by so first. We have one week left but I still have so much to say. Life has some crazy ups and downs but going through them with you keeps me sane. You represent so much stability in my life. I talk about how you make me calm and safe but not enough about how that’s a beautiful charachter that you potray. You have a heart of gold and such a beautiful soul. You’re really slow to anger and even when you’re disappointed or hurt you carry yourself with so much grace. You’re voice of reason even in the most chaotic times. You lead with love in everything that you do and it shows so much in your life. You remind me everyday what love is because you are so full of it. Days seem like seconds with you and I hope to feel that forever. Here’s to Day 15 of 22💗", order: 14 },
      { _id: "16", text: "Happy Friday baby! I know right now you’re a bit stressed out because of your exams. I just want to assure you that you’ll do great. You’re one of the people who I know who do so much hard work. You deserve all the good things in this life and I hope you get them. As this period starts I hope you know that I’m there whenever you need anything. When you need to decompress I’m just a call away. I hope that this time goes by so smoothly and that you can see the fruits of your hard work. You’re smart and capable and so close to closing off a huge chapter in your life. I believe in you today and always! Happy day 16 of 22💗", order: 15 },
      { _id: "17", text: "One thing that I see in your life is that you are bound for success. You go through life putting your all in everything that you do. You believe in yourself more than anyone else does and in turn everyone around you does so too! I hope you know that I want to take this journey with you. Through the highs and lows and the days where it’s an inbetween. I want to be the shoulder that you can lean on for anything that you need.  You always tell me that you’re here for me and I want to assure you that I’m here for you too in any and every way that I can. To give you the same support and care that you do. Choosing you has been the best decision I made this year and I’ll continue to choose you everyday. Here’s yo day 17 of 22💗", order: 16 },
      { _id: "18", text: "Happy Sunday and Happy Birthday week!! I’m so excited to get to celebrate this week with you. Literally been trying to stay calm. You deserve all the good things this life has to offer and I’ll never stop reminding you of that. I pray and home that as you start this week you you go into every challenge you may face with a strong mind and heart. As you also do your exams I pray that your mind is at ease and that you have confidence through all of them. I’m right here next to you cheering you on and supporting you! I can’t wait for you to be done so I can get the chance to show you how much you mean to me and how much you deserve. To a week of success, love and celebrations PS: Success in Machine Learning tomorrow!! Here’s to day 18 of 22💗", order: 17 },
      { _id: "19", text: "First exam done🥳🥳. Starting off by saying that I am extremely proud of you today and everyday. I know that you’ll be great this week and that you are putting your best foot forward. I admire your work ethic and how much you push yourself. You are definitely a force to be reckoned with and one to watch out for. I continue to wish you the best even right now as you read for tomorrow’s paper. I hope you remember to take some time to breathe and let out some stress. You’re very capable in everything that you do and I know you will do great! I love you, I am proud of you and you’re so special. Good luck with distributed systems tomorrow💗 Here’s to day 19 of 22💗", order: 18 },
      { _id: "20", text: "I can’t believe this series is coming to an end. I’ve enjoyed every second of the last 20 days and I hope you have to. You make my days brighter and better. I loved doing this exercise because it exposed me to so much that I love most of which I couldn’t even explain with words but found myself doing so. You complete me in so many ways and I’m grateful to experience life with you. You are not only the epitome of love but of life as well. You radiate so much warmth and have such a soft heart. You remind me everyday that good things in this world still exist. You love fully and whole heartedly and it makes me want to do so and more. You’ve created so much space for me in your life that I feel completely at home when I’m with you! I love you so much! Happy day 20 of 22💗", order: 19 },
      { _id: "21", text: "Last day being 21🥳🥳🥳🥳. Time flies so much right. I hope that you look at the year you’ve had and feel accomplished. I hope you got to achieve the goals you set out for yourself in your 21st year. These are just the beginning of your 20s and dare I say your life. You have so much to give this world and I can’t wait to see you take on this world. I know the past year hasn’t been all smooth sailing ofcourse but look at you! You got through all the bad times and got to enjoy the good ones too. I met you when you were half way through it but I’m glad I did. I’m glad life led me into your direction because you are exactly who I want to get through what life has to offer. Today marks the end of another year in your life. It also marks the beginning of a new age one that I’m sure will come with greatness but I’ll tell you all that tomorrow. For now do me a favour and go get yourself the 21 candles and wait for something from me. I love you💗 Good luck with Social Informatics! Here’s to day 21 of 22💗", order: 20 }
    ];
  }

  async findAll() {
    console.log('Returning all default messages');
    return this.messages;
  }

  async create(messageData) {
    const newMessage = {
      _id: new Date().getTime().toString(),
      text: messageData.text,
      order: this.messages.length
    };
    this.messages.push(newMessage);
    return newMessage;
  }
}

const messageService = new MessageService();

module.exports = {
  messageService
};
